"""empty message

Revision ID: 47b74d985605
Revises: None
Create Date: 2015-11-13 13:37:44.898472

"""

# revision identifiers, used by Alembic.
revision = '47b74d985605'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('NeverUnfollowAccounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=True),
    sa.Column('accountname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WhitelistKeywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=64), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GeneralSettings',
    sa.Column('fk_user_id', sa.Integer(), nullable=False),
    sa.Column('consumer_key', sa.String(length=64), nullable=True),
    sa.Column('consumer_secret', sa.String(length=64), nullable=True),
    sa.Column('access_token', sa.String(length=64), nullable=True),
    sa.Column('access_token_secret', sa.String(length=64), nullable=True),
    sa.Column('own_twittername', sa.String(length=64), nullable=True),
    sa.Column('max_updates_per_day', sa.Integer(), nullable=True),
    sa.Column('status_update_score', sa.Integer(), nullable=True),
    sa.Column('follow_score', sa.Integer(), nullable=True),
    sa.Column('retweet_score', sa.Integer(), nullable=True),
    sa.Column('favorite_score', sa.Integer(), nullable=True),
    sa.Column('number_active_favorites', sa.Integer(), nullable=True),
    sa.Column('number_active_retweets', sa.Integer(), nullable=True),
    sa.Column('number_active_follows', sa.Integer(), nullable=True),
    sa.Column('only_with_url', sa.Integer(), nullable=True),
    sa.Column('payed_active', sa.Integer(), nullable=True),
    sa.Column('test_active', sa.Integer(), nullable=True),
    sa.Column('onoff', sa.Integer(), nullable=True),
    sa.Column('restart_needed', sa.Integer(), nullable=True),
    sa.Column('paused_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('fk_user_id'),
    sa.UniqueConstraint('own_twittername')
    )
    op.create_index('ix_GeneralSettings_fk_user_id', 'GeneralSettings', ['fk_user_id'], unique=False)
    op.create_table('BlacklistKeywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=64), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('connection_settings_set', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', 'users')
    op.drop_index('ix_users_email', 'users')
    op.drop_table('users')
    op.drop_table('BlacklistKeywords')
    op.drop_index('ix_GeneralSettings_fk_user_id', 'GeneralSettings')
    op.drop_table('GeneralSettings')
    op.drop_table('WhitelistKeywords')
    op.drop_table('NeverUnfollowAccounts')
    op.drop_table('roles')
    ### end Alembic commands ###
